'use strict';
// Builds src/starcat.js from the HYG database (https://github.com/astronexus/HYG-Database, CC BY-SA 4.0):
//   node tools/build_starcat.js hygdata_v41.csv
// Keeps every star to magnitude 7.0 except the ones the game models as real bodies. Per star, five uint16:
// right ascension, declination, log10 distance (pc; 65535 = unknown), magnitude, B-V colour index.
const fs = require('fs');
const MAG_MAX = 7.0;
const SKIP = new Set(['0', '71456', '71453', '70666', '87665', '16496']);   // Sol, α Cen A/B, Proxima, Barnard's, ε Eri
const lines = fs.readFileSync(process.argv[2], 'utf8').split('\n');
const head = JSON.parse('[' + lines[0] + ']');
const col = (n) => head.indexOf(n);
const I = { id: col('id'), ra: col('ra'), dec: col('dec'), dist: col('dist'), mag: col('mag'), ci: col('ci') };
function parse(l) { const o = []; let cur = '', q = false; for (const ch of l) { if (ch === '"') { q = !q; continue; } if (ch === ',' && !q) { o.push(cur); cur = ''; continue; } cur += ch; } o.push(cur); return o; }
const rows = [];
for (const l of lines.slice(1)) {
  if (!l) continue;
  const r = parse(l);
  if (SKIP.has(r[I.id]) || !(+r[I.mag] <= MAG_MAX)) continue;
  rows.push(r);
}
rows.sort((a, b) => +a[I.mag] - +b[I.mag]);
const u16 = new Uint16Array(rows.length * 5);
const q = (x, lo, hi) => Math.max(0, Math.min(65534, Math.round((x - lo) / (hi - lo) * 65534)));
rows.forEach((r, i) => {
  const d = +r[I.dist], ci = r[I.ci] === '' ? 0.65 : +r[I.ci];
  u16[i * 5] = q(+r[I.ra], 0, 24);
  u16[i * 5 + 1] = q(+r[I.dec], -90, 90);
  u16[i * 5 + 2] = d > 0 && d < 99999 ? q(Math.log10(d), -1, 5) : 65535;
  u16[i * 5 + 3] = q(+r[I.mag], -2, 8);
  u16[i * 5 + 4] = q(ci, -0.5, 3.5);
});
const b64 = Buffer.from(u16.buffer).toString('base64');
const out = `'use strict';
// Generated by tools/build_starcat.js from the HYG database v4.1 (astronexus, CC BY-SA 4.0). Do not edit.
// ${rows.length} stars to magnitude ${MAG_MAX}, brightest first; 5 x uint16 per star: RA, Dec, log10 dist pc, mag, B-V.
const STARCAT = { n: ${rows.length}, data: '${b64}' };
`;
fs.writeFileSync(__dirname + '/../src/starcat.js', out);
console.log('stars', rows.length, 'bytes', out.length);
